// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.20.3
// source: runner.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Signal int32

const (
	Signal_SIGNAL_UNSPECIFIED Signal = 0
	Signal_SIGNAL_SIGINT      Signal = 2
	Signal_SIGNAL_SIGKILL     Signal = 9
	Signal_SIGNAL_SIGTERM     Signal = 15
)

// Enum value maps for Signal.
var (
	Signal_name = map[int32]string{
		0:  "SIGNAL_UNSPECIFIED",
		2:  "SIGNAL_SIGINT",
		9:  "SIGNAL_SIGKILL",
		15: "SIGNAL_SIGTERM",
	}
	Signal_value = map[string]int32{
		"SIGNAL_UNSPECIFIED": 0,
		"SIGNAL_SIGINT":      2,
		"SIGNAL_SIGKILL":     9,
		"SIGNAL_SIGTERM":     15,
	}
)

func (x Signal) Enum() *Signal {
	p := new(Signal)
	*p = x
	return p
}

func (x Signal) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Signal) Descriptor() protoreflect.EnumDescriptor {
	return file_runner_proto_enumTypes[0].Descriptor()
}

func (Signal) Type() protoreflect.EnumType {
	return &file_runner_proto_enumTypes[0]
}

func (x Signal) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Signal) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Signal(num)
	return nil
}

// Deprecated: Use Signal.Descriptor instead.
func (Signal) EnumDescriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{0}
}

type InstanceType int32

const (
	InstanceType_INSTANCE_TYPE_UNSPECIFIED InstanceType = 0
	InstanceType_INSTANCE_TYPE_MICRO       InstanceType = 1
	InstanceType_INSTANCE_TYPE_SMALL       InstanceType = 2
	InstanceType_INSTANCE_TYPE_MEDIUM      InstanceType = 3
	InstanceType_INSTANCE_TYPE_LARGE       InstanceType = 4
	InstanceType_INSTANCE_TYPE_XLARGE      InstanceType = 5
)

// Enum value maps for InstanceType.
var (
	InstanceType_name = map[int32]string{
		0: "INSTANCE_TYPE_UNSPECIFIED",
		1: "INSTANCE_TYPE_MICRO",
		2: "INSTANCE_TYPE_SMALL",
		3: "INSTANCE_TYPE_MEDIUM",
		4: "INSTANCE_TYPE_LARGE",
		5: "INSTANCE_TYPE_XLARGE",
	}
	InstanceType_value = map[string]int32{
		"INSTANCE_TYPE_UNSPECIFIED": 0,
		"INSTANCE_TYPE_MICRO":       1,
		"INSTANCE_TYPE_SMALL":       2,
		"INSTANCE_TYPE_MEDIUM":      3,
		"INSTANCE_TYPE_LARGE":       4,
		"INSTANCE_TYPE_XLARGE":      5,
	}
)

func (x InstanceType) Enum() *InstanceType {
	p := new(InstanceType)
	*p = x
	return p
}

func (x InstanceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstanceType) Descriptor() protoreflect.EnumDescriptor {
	return file_runner_proto_enumTypes[1].Descriptor()
}

func (InstanceType) Type() protoreflect.EnumType {
	return &file_runner_proto_enumTypes[1]
}

func (x InstanceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *InstanceType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = InstanceType(num)
	return nil
}

// Deprecated: Use InstanceType.Descriptor instead.
func (InstanceType) EnumDescriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{1}
}

type SandboxState int32

const (
	SandboxState_SANDBOX_STATE_UNSPECIFIED SandboxState = 0
	SandboxState_SANDBOX_STATE_PENDING     SandboxState = 1
	SandboxState_SANDBOX_STATE_RUNNING     SandboxState = 2
	SandboxState_SANDBOX_STATE_TERMINATING SandboxState = 3
	SandboxState_SANDBOX_STATE_TERMINATED  SandboxState = 4
	SandboxState_SANDBOX_STATE_FAILED      SandboxState = 5
	SandboxState_SANDBOX_STATE_PAUSED      SandboxState = 6
)

// Enum value maps for SandboxState.
var (
	SandboxState_name = map[int32]string{
		0: "SANDBOX_STATE_UNSPECIFIED",
		1: "SANDBOX_STATE_PENDING",
		2: "SANDBOX_STATE_RUNNING",
		3: "SANDBOX_STATE_TERMINATING",
		4: "SANDBOX_STATE_TERMINATED",
		5: "SANDBOX_STATE_FAILED",
		6: "SANDBOX_STATE_PAUSED",
	}
	SandboxState_value = map[string]int32{
		"SANDBOX_STATE_UNSPECIFIED": 0,
		"SANDBOX_STATE_PENDING":     1,
		"SANDBOX_STATE_RUNNING":     2,
		"SANDBOX_STATE_TERMINATING": 3,
		"SANDBOX_STATE_TERMINATED":  4,
		"SANDBOX_STATE_FAILED":      5,
		"SANDBOX_STATE_PAUSED":      6,
	}
)

func (x SandboxState) Enum() *SandboxState {
	p := new(SandboxState)
	*p = x
	return p
}

func (x SandboxState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SandboxState) Descriptor() protoreflect.EnumDescriptor {
	return file_runner_proto_enumTypes[2].Descriptor()
}

func (SandboxState) Type() protoreflect.EnumType {
	return &file_runner_proto_enumTypes[2]
}

func (x SandboxState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SandboxState) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SandboxState(num)
	return nil
}

// Deprecated: Use SandboxState.Descriptor instead.
func (SandboxState) EnumDescriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{2}
}

type PTY struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          *uint32                `protobuf:"varint,1,req,name=cols" json:"cols,omitempty"`
	Rows          *uint32                `protobuf:"varint,2,req,name=rows" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTY) Reset() {
	*x = PTY{}
	mi := &file_runner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTY) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTY) ProtoMessage() {}

func (x *PTY) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTY.ProtoReflect.Descriptor instead.
func (*PTY) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{0}
}

func (x *PTY) GetCols() uint32 {
	if x != nil && x.Cols != nil {
		return *x.Cols
	}
	return 0
}

func (x *PTY) GetRows() uint32 {
	if x != nil && x.Rows != nil {
		return *x.Rows
	}
	return 0
}

type ProcessConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       []string               `protobuf:"bytes,1,rep,name=command" json:"command,omitempty"`
	EnvVars       map[string]string      `protobuf:"bytes,2,rep,name=env_vars,json=envVars" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Cwd           *string                `protobuf:"bytes,3,opt,name=cwd" json:"cwd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessConfig) Reset() {
	*x = ProcessConfig{}
	mi := &file_runner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessConfig) ProtoMessage() {}

func (x *ProcessConfig) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessConfig.ProtoReflect.Descriptor instead.
func (*ProcessConfig) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessConfig) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ProcessConfig) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *ProcessConfig) GetCwd() string {
	if x != nil && x.Cwd != nil {
		return *x.Cwd
	}
	return ""
}

type ExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *ProcessConfig         `protobuf:"bytes,1,req,name=config" json:"config,omitempty"`
	Pty           *PTY                   `protobuf:"bytes,2,opt,name=pty" json:"pty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_runner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{2}
}

func (x *ExecRequest) GetConfig() *ProcessConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ExecRequest) GetPty() *PTY {
	if x != nil {
		return x.Pty
	}
	return nil
}

type InitEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessId     *int32                 `protobuf:"varint,1,req,name=process_id,json=processId" json:"process_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitEvent) Reset() {
	*x = InitEvent{}
	mi := &file_runner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitEvent) ProtoMessage() {}

func (x *InitEvent) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitEvent.ProtoReflect.Descriptor instead.
func (*InitEvent) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{3}
}

func (x *InitEvent) GetProcessId() int32 {
	if x != nil && x.ProcessId != nil {
		return *x.ProcessId
	}
	return 0
}

type ExitEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      *int32                 `protobuf:"varint,1,req,name=exit_code,json=exitCode" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitEvent) Reset() {
	*x = ExitEvent{}
	mi := &file_runner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitEvent) ProtoMessage() {}

func (x *ExitEvent) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitEvent.ProtoReflect.Descriptor instead.
func (*ExitEvent) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{4}
}

func (x *ExitEvent) GetExitCode() int32 {
	if x != nil && x.ExitCode != nil {
		return *x.ExitCode
	}
	return 0
}

type AsyncExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Init          *InitEvent             `protobuf:"bytes,1,opt,name=init" json:"init,omitempty"`
	Stdout        []byte                 `protobuf:"bytes,2,opt,name=stdout" json:"stdout,omitempty"`
	Stderr        []byte                 `protobuf:"bytes,3,opt,name=stderr" json:"stderr,omitempty"`
	Exit          *ExitEvent             `protobuf:"bytes,4,opt,name=exit" json:"exit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsyncExecResponse) Reset() {
	*x = AsyncExecResponse{}
	mi := &file_runner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsyncExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncExecResponse) ProtoMessage() {}

func (x *AsyncExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsyncExecResponse.ProtoReflect.Descriptor instead.
func (*AsyncExecResponse) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{5}
}

func (x *AsyncExecResponse) GetInit() *InitEvent {
	if x != nil {
		return x.Init
	}
	return nil
}

func (x *AsyncExecResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *AsyncExecResponse) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *AsyncExecResponse) GetExit() *ExitEvent {
	if x != nil {
		return x.Exit
	}
	return nil
}

// ExecuteResponse contains the complete output of a synchronously executed command.
type SyncExecResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Process exit code (0 indicates success).
	ExitCode *int32 `protobuf:"varint,1,req,name=exit_code,json=exitCode" json:"exit_code,omitempty"`
	// Combined standard output buffer produced during execution.
	Stdout []byte `protobuf:"bytes,2,req,name=stdout" json:"stdout,omitempty"`
	// Combined standard error buffer produced during execution.
	Stderr        []byte `protobuf:"bytes,3,req,name=stderr" json:"stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncExecResponse) Reset() {
	*x = SyncExecResponse{}
	mi := &file_runner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncExecResponse) ProtoMessage() {}

func (x *SyncExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncExecResponse.ProtoReflect.Descriptor instead.
func (*SyncExecResponse) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{6}
}

func (x *SyncExecResponse) GetExitCode() int32 {
	if x != nil && x.ExitCode != nil {
		return *x.ExitCode
	}
	return 0
}

func (x *SyncExecResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *SyncExecResponse) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

type SendSignalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessId     *int32                 `protobuf:"varint,1,req,name=process_id,json=processId" json:"process_id,omitempty"`
	Signal        *Signal                `protobuf:"varint,2,req,name=signal,enum=Signal" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSignalRequest) Reset() {
	*x = SendSignalRequest{}
	mi := &file_runner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSignalRequest) ProtoMessage() {}

func (x *SendSignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSignalRequest.ProtoReflect.Descriptor instead.
func (*SendSignalRequest) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{7}
}

func (x *SendSignalRequest) GetProcessId() int32 {
	if x != nil && x.ProcessId != nil {
		return *x.ProcessId
	}
	return 0
}

func (x *SendSignalRequest) GetSignal() Signal {
	if x != nil && x.Signal != nil {
		return *x.Signal
	}
	return Signal_SIGNAL_UNSPECIFIED
}

type SendSignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSignalResponse) Reset() {
	*x = SendSignalResponse{}
	mi := &file_runner_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSignalResponse) ProtoMessage() {}

func (x *SendSignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSignalResponse.ProtoReflect.Descriptor instead.
func (*SendSignalResponse) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{8}
}

type WriteStdinRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ProcessId *int32                 `protobuf:"varint,1,req,name=process_id,json=processId" json:"process_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WriteStdinRequest_Input
	//	*WriteStdinRequest_Eof
	Payload       isWriteStdinRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteStdinRequest) Reset() {
	*x = WriteStdinRequest{}
	mi := &file_runner_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteStdinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteStdinRequest) ProtoMessage() {}

func (x *WriteStdinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteStdinRequest.ProtoReflect.Descriptor instead.
func (*WriteStdinRequest) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{9}
}

func (x *WriteStdinRequest) GetProcessId() int32 {
	if x != nil && x.ProcessId != nil {
		return *x.ProcessId
	}
	return 0
}

func (x *WriteStdinRequest) GetPayload() isWriteStdinRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WriteStdinRequest) GetInput() []byte {
	if x != nil {
		if x, ok := x.Payload.(*WriteStdinRequest_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *WriteStdinRequest) GetEof() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Payload.(*WriteStdinRequest_Eof); ok {
			return x.Eof
		}
	}
	return nil
}

type isWriteStdinRequest_Payload interface {
	isWriteStdinRequest_Payload()
}

type WriteStdinRequest_Input struct {
	Input []byte `protobuf:"bytes,2,opt,name=input,oneof"`
}

type WriteStdinRequest_Eof struct {
	Eof *emptypb.Empty `protobuf:"bytes,3,opt,name=eof,oneof"`
}

func (*WriteStdinRequest_Input) isWriteStdinRequest_Payload() {}

func (*WriteStdinRequest_Eof) isWriteStdinRequest_Payload() {}

type WriteStdinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteStdinResponse) Reset() {
	*x = WriteStdinResponse{}
	mi := &file_runner_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteStdinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteStdinResponse) ProtoMessage() {}

func (x *WriteStdinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteStdinResponse.ProtoReflect.Descriptor instead.
func (*WriteStdinResponse) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{10}
}

type UploadFileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          *string                `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,req,name=content" json:"content,omitempty"`
	Mode          *uint32                `protobuf:"varint,3,opt,name=mode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileChunk) Reset() {
	*x = UploadFileChunk{}
	mi := &file_runner_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileChunk) ProtoMessage() {}

func (x *UploadFileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileChunk.ProtoReflect.Descriptor instead.
func (*UploadFileChunk) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{11}
}

func (x *UploadFileChunk) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *UploadFileChunk) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *UploadFileChunk) GetMode() uint32 {
	if x != nil && x.Mode != nil {
		return *x.Mode
	}
	return 0
}

type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_runner_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{12}
}

type DownloadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          *string                `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileRequest) Reset() {
	*x = DownloadFileRequest{}
	mi := &file_runner_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileRequest) ProtoMessage() {}

func (x *DownloadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileRequest.ProtoReflect.Descriptor instead.
func (*DownloadFileRequest) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{13}
}

func (x *DownloadFileRequest) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

type DownloadFileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,req,name=content" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileChunk) Reset() {
	*x = DownloadFileChunk{}
	mi := &file_runner_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileChunk) ProtoMessage() {}

func (x *DownloadFileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileChunk.ProtoReflect.Descriptor instead.
func (*DownloadFileChunk) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{14}
}

func (x *DownloadFileChunk) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type ListFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          *string                `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_runner_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{15}
}

func (x *ListFilesRequest) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          *string                `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	Size          *uint64                `protobuf:"varint,2,req,name=size" json:"size,omitempty"`
	IsDir         *bool                  `protobuf:"varint,3,req,name=is_dir,json=isDir" json:"is_dir,omitempty"`
	Mode          *uint32                `protobuf:"varint,4,opt,name=mode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_runner_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{16}
}

func (x *FileInfo) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *FileInfo) GetSize() uint64 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

func (x *FileInfo) GetIsDir() bool {
	if x != nil && x.IsDir != nil {
		return *x.IsDir
	}
	return false
}

func (x *FileInfo) GetMode() uint32 {
	if x != nil && x.Mode != nil {
		return *x.Mode
	}
	return 0
}

type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*FileInfo            `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_runner_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{17}
}

func (x *ListFilesResponse) GetEntries() []*FileInfo {
	if x != nil {
		return x.Entries
	}
	return nil
}

type RemoveFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          *string                `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	Recursive     *bool                  `protobuf:"varint,2,opt,name=recursive" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFileRequest) Reset() {
	*x = RemoveFileRequest{}
	mi := &file_runner_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFileRequest) ProtoMessage() {}

func (x *RemoveFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFileRequest.ProtoReflect.Descriptor instead.
func (*RemoveFileRequest) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{18}
}

func (x *RemoveFileRequest) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *RemoveFileRequest) GetRecursive() bool {
	if x != nil && x.Recursive != nil {
		return *x.Recursive
	}
	return false
}

type RemoveFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFileResponse) Reset() {
	*x = RemoveFileResponse{}
	mi := &file_runner_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFileResponse) ProtoMessage() {}

func (x *RemoveFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFileResponse.ProtoReflect.Descriptor instead.
func (*RemoveFileResponse) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{19}
}

type ResourceLimits struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Cpu                    *string                `protobuf:"bytes,1,req,name=cpu" json:"cpu,omitempty"`
	MemoryInMbs            *int32                 `protobuf:"varint,2,req,name=memory_in_mbs,json=memoryInMbs" json:"memory_in_mbs,omitempty"`
	StorageInMbs           *int32                 `protobuf:"varint,3,opt,name=storage_in_mbs,json=storageInMbs" json:"storage_in_mbs,omitempty"`
	NetworkBandwidthInMbps *int32                 `protobuf:"varint,4,opt,name=network_bandwidth_in_mbps,json=networkBandwidthInMbps" json:"network_bandwidth_in_mbps,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	mi := &file_runner_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimits.ProtoReflect.Descriptor instead.
func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{20}
}

func (x *ResourceLimits) GetCpu() string {
	if x != nil && x.Cpu != nil {
		return *x.Cpu
	}
	return ""
}

func (x *ResourceLimits) GetMemoryInMbs() int32 {
	if x != nil && x.MemoryInMbs != nil {
		return *x.MemoryInMbs
	}
	return 0
}

func (x *ResourceLimits) GetStorageInMbs() int32 {
	if x != nil && x.StorageInMbs != nil {
		return *x.StorageInMbs
	}
	return 0
}

func (x *ResourceLimits) GetNetworkBandwidthInMbps() int32 {
	if x != nil && x.NetworkBandwidthInMbps != nil {
		return *x.NetworkBandwidthInMbps
	}
	return 0
}

type NetworkSettings struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EnableInternet     *bool                  `protobuf:"varint,1,opt,name=enable_internet,json=enableInternet" json:"enable_internet,omitempty"`
	AllowedEgressCidrs []string               `protobuf:"bytes,2,rep,name=allowed_egress_cidrs,json=allowedEgressCidrs" json:"allowed_egress_cidrs,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NetworkSettings) Reset() {
	*x = NetworkSettings{}
	mi := &file_runner_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkSettings) ProtoMessage() {}

func (x *NetworkSettings) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkSettings.ProtoReflect.Descriptor instead.
func (*NetworkSettings) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{21}
}

func (x *NetworkSettings) GetEnableInternet() bool {
	if x != nil && x.EnableInternet != nil {
		return *x.EnableInternet
	}
	return false
}

func (x *NetworkSettings) GetAllowedEgressCidrs() []string {
	if x != nil {
		return x.AllowedEgressCidrs
	}
	return nil
}

// SandboxProfileSpec is the blueprint for a sandbox: every trait needed to
// produce one, plus the pool-sizing knobs that control how many warm
// instances of it are kept ready.
type SandboxProfileSpec struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TemplateId             *string                `protobuf:"bytes,1,req,name=template_id,json=templateId" json:"template_id,omitempty"`
	Cwd                    *string                `protobuf:"bytes,2,opt,name=cwd" json:"cwd,omitempty"`
	Tags                   map[string]string      `protobuf:"bytes,4,rep,name=tags" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EnvVars                map[string]string      `protobuf:"bytes,5,rep,name=env_vars,json=envVars" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AutoDeleteAfterSeconds *uint32                `protobuf:"varint,7,opt,name=auto_delete_after_seconds,json=autoDeleteAfterSeconds" json:"auto_delete_after_seconds,omitempty"`
	Region                 *string                `protobuf:"bytes,9,opt,name=region" json:"region,omitempty"`
	Network                *NetworkSettings       `protobuf:"bytes,10,opt,name=network" json:"network,omitempty"`
	// Types that are valid to be assigned to Compute:
	//
	//	*SandboxProfileSpec_Resources
	//	*SandboxProfileSpec_InstanceType
	Compute isSandboxProfileSpec_Compute `protobuf_oneof:"compute"`
	// ahead_concurrency is the warm pool size: how many instances of this
	// profile are kept pre-booted to avoid cold starts.
	AheadConcurrency *uint32 `protobuf:"varint,11,opt,name=ahead_concurrency,json=aheadConcurrency" json:"ahead_concurrency,omitempty"`
	// concurrency_limit caps how many sandboxes of this profile may be
	// claimed and running at the same time.
	ConcurrencyLimit *uint32 `protobuf:"varint,12,opt,name=concurrency_limit,json=concurrencyLimit" json:"concurrency_limit,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SandboxProfileSpec) Reset() {
	*x = SandboxProfileSpec{}
	mi := &file_runner_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxProfileSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxProfileSpec) ProtoMessage() {}

func (x *SandboxProfileSpec) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxProfileSpec.ProtoReflect.Descriptor instead.
func (*SandboxProfileSpec) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{22}
}

func (x *SandboxProfileSpec) GetTemplateId() string {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return ""
}

func (x *SandboxProfileSpec) GetCwd() string {
	if x != nil && x.Cwd != nil {
		return *x.Cwd
	}
	return ""
}

func (x *SandboxProfileSpec) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SandboxProfileSpec) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *SandboxProfileSpec) GetAutoDeleteAfterSeconds() uint32 {
	if x != nil && x.AutoDeleteAfterSeconds != nil {
		return *x.AutoDeleteAfterSeconds
	}
	return 0
}

func (x *SandboxProfileSpec) GetRegion() string {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	return ""
}

func (x *SandboxProfileSpec) GetNetwork() *NetworkSettings {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *SandboxProfileSpec) GetCompute() isSandboxProfileSpec_Compute {
	if x != nil {
		return x.Compute
	}
	return nil
}

func (x *SandboxProfileSpec) GetResources() *ResourceLimits {
	if x != nil {
		if x, ok := x.Compute.(*SandboxProfileSpec_Resources); ok {
			return x.Resources
		}
	}
	return nil
}

func (x *SandboxProfileSpec) GetInstanceType() InstanceType {
	if x != nil {
		if x, ok := x.Compute.(*SandboxProfileSpec_InstanceType); ok {
			return x.InstanceType
		}
	}
	return InstanceType_INSTANCE_TYPE_UNSPECIFIED
}

func (x *SandboxProfileSpec) GetAheadConcurrency() uint32 {
	if x != nil && x.AheadConcurrency != nil {
		return *x.AheadConcurrency
	}
	return 0
}

func (x *SandboxProfileSpec) GetConcurrencyLimit() uint32 {
	if x != nil && x.ConcurrencyLimit != nil {
		return *x.ConcurrencyLimit
	}
	return 0
}

type isSandboxProfileSpec_Compute interface {
	isSandboxProfileSpec_Compute()
}

type SandboxProfileSpec_Resources struct {
	Resources *ResourceLimits `protobuf:"bytes,6,opt,name=resources,oneof"`
}

type SandboxProfileSpec_InstanceType struct {
	InstanceType InstanceType `protobuf:"varint,8,opt,name=instance_type,json=instanceType,enum=InstanceType,oneof"`
}

func (*SandboxProfileSpec_Resources) isSandboxProfileSpec_Compute() {}

func (*SandboxProfileSpec_InstanceType) isSandboxProfileSpec_Compute() {}

// SandboxProfile is a created, addressable SandboxProfileSpec. Sandboxes are
// always claimed against a profile_id, never against a raw spec.
type SandboxProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     *string                `protobuf:"bytes,1,req,name=profile_id,json=profileId" json:"profile_id,omitempty"`
	Spec          *SandboxProfileSpec    `protobuf:"bytes,2,req,name=spec" json:"spec,omitempty"`
	CreatedAt     *int64                 `protobuf:"varint,3,req,name=created_at,json=createdAt" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxProfile) Reset() {
	*x = SandboxProfile{}
	mi := &file_runner_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxProfile) ProtoMessage() {}

func (x *SandboxProfile) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxProfile.ProtoReflect.Descriptor instead.
func (*SandboxProfile) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{23}
}

func (x *SandboxProfile) GetProfileId() string {
	if x != nil && x.ProfileId != nil {
		return *x.ProfileId
	}
	return ""
}

func (x *SandboxProfile) GetSpec() *SandboxProfileSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *SandboxProfile) GetCreatedAt() int64 {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return 0
}

type CreateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *SandboxProfileSpec    `protobuf:"bytes,1,req,name=spec" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileRequest) Reset() {
	*x = CreateProfileRequest{}
	mi := &file_runner_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileRequest) ProtoMessage() {}

func (x *CreateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateProfileRequest) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{24}
}

func (x *CreateProfileRequest) GetSpec() *SandboxProfileSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type CreateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *SandboxProfile        `protobuf:"bytes,1,req,name=profile" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileResponse) Reset() {
	*x = CreateProfileResponse{}
	mi := &file_runner_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileResponse) ProtoMessage() {}

func (x *CreateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileResponse.ProtoReflect.Descriptor instead.
func (*CreateProfileResponse) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{25}
}

func (x *CreateProfileResponse) GetProfile() *SandboxProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     *string                `protobuf:"bytes,1,req,name=profile_id,json=profileId" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_runner_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{26}
}

func (x *GetProfileRequest) GetProfileId() string {
	if x != nil && x.ProfileId != nil {
		return *x.ProfileId
	}
	return ""
}

type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *SandboxProfile        `protobuf:"bytes,1,req,name=profile" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_runner_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{27}
}

func (x *GetProfileResponse) GetProfile() *SandboxProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type ListProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      *uint32                `protobuf:"varint,1,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	PageToken     *string                `protobuf:"bytes,2,opt,name=page_token,json=pageToken" json:"page_token,omitempty"`
	LabelSelector map[string]string      `protobuf:"bytes,3,rep,name=label_selector,json=labelSelector" json:"label_selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesRequest) Reset() {
	*x = ListProfilesRequest{}
	mi := &file_runner_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesRequest) ProtoMessage() {}

func (x *ListProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesRequest.ProtoReflect.Descriptor instead.
func (*ListProfilesRequest) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{28}
}

func (x *ListProfilesRequest) GetPageSize() uint32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListProfilesRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

func (x *ListProfilesRequest) GetLabelSelector() map[string]string {
	if x != nil {
		return x.LabelSelector
	}
	return nil
}

type ListProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*SandboxProfile      `protobuf:"bytes,1,rep,name=profiles" json:"profiles,omitempty"`
	NextPageToken *string                `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesResponse) Reset() {
	*x = ListProfilesResponse{}
	mi := &file_runner_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesResponse) ProtoMessage() {}

func (x *ListProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesResponse.ProtoReflect.Descriptor instead.
func (*ListProfilesResponse) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{29}
}

func (x *ListProfilesResponse) GetProfiles() []*SandboxProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

func (x *ListProfilesResponse) GetNextPageToken() string {
	if x != nil && x.NextPageToken != nil {
		return *x.NextPageToken
	}
	return ""
}

type DeleteProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     *string                `protobuf:"bytes,1,req,name=profile_id,json=profileId" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProfileRequest) Reset() {
	*x = DeleteProfileRequest{}
	mi := &file_runner_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfileRequest) ProtoMessage() {}

func (x *DeleteProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfileRequest.ProtoReflect.Descriptor instead.
func (*DeleteProfileRequest) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{30}
}

func (x *DeleteProfileRequest) GetProfileId() string {
	if x != nil && x.ProfileId != nil {
		return *x.ProfileId
	}
	return ""
}

type DeleteProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProfileResponse) Reset() {
	*x = DeleteProfileResponse{}
	mi := &file_runner_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfileResponse) ProtoMessage() {}

func (x *DeleteProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfileResponse.ProtoReflect.Descriptor instead.
func (*DeleteProfileResponse) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{31}
}

type Sandbox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     *string                `protobuf:"bytes,1,req,name=sandbox_id,json=sandboxId" json:"sandbox_id,omitempty"`
	State         *SandboxState          `protobuf:"varint,2,req,name=state,enum=SandboxState" json:"state,omitempty"`
	ProfileId     *string                `protobuf:"bytes,3,req,name=profile_id,json=profileId" json:"profile_id,omitempty"`
	CreatedAt     *int64                 `protobuf:"varint,4,req,name=created_at,json=createdAt" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sandbox) Reset() {
	*x = Sandbox{}
	mi := &file_runner_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sandbox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sandbox) ProtoMessage() {}

func (x *Sandbox) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sandbox.ProtoReflect.Descriptor instead.
func (*Sandbox) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{32}
}

func (x *Sandbox) GetSandboxId() string {
	if x != nil && x.SandboxId != nil {
		return *x.SandboxId
	}
	return ""
}

func (x *Sandbox) GetState() SandboxState {
	if x != nil && x.State != nil {
		return *x.State
	}
	return SandboxState_SANDBOX_STATE_UNSPECIFIED
}

func (x *Sandbox) GetProfileId() string {
	if x != nil && x.ProfileId != nil {
		return *x.ProfileId
	}
	return ""
}

func (x *Sandbox) GetCreatedAt() int64 {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return 0
}

// ClaimSandboxRequest claims a sandbox. The profile can already exist
// (claim by profile_id, the ahead-of-time path) or be created on demand by
// supplying its spec inline — either way the result is a sandbox bound to a
// profile.
type ClaimSandboxRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Target:
	//
	//	*ClaimSandboxRequest_ProfileId
	//	*ClaimSandboxRequest_Profile
	Target        isClaimSandboxRequest_Target `protobuf_oneof:"target"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimSandboxRequest) Reset() {
	*x = ClaimSandboxRequest{}
	mi := &file_runner_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimSandboxRequest) ProtoMessage() {}

func (x *ClaimSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimSandboxRequest.ProtoReflect.Descriptor instead.
func (*ClaimSandboxRequest) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{33}
}

func (x *ClaimSandboxRequest) GetTarget() isClaimSandboxRequest_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ClaimSandboxRequest) GetProfileId() string {
	if x != nil {
		if x, ok := x.Target.(*ClaimSandboxRequest_ProfileId); ok {
			return x.ProfileId
		}
	}
	return ""
}

func (x *ClaimSandboxRequest) GetProfile() *SandboxProfileSpec {
	if x != nil {
		if x, ok := x.Target.(*ClaimSandboxRequest_Profile); ok {
			return x.Profile
		}
	}
	return nil
}

type isClaimSandboxRequest_Target interface {
	isClaimSandboxRequest_Target()
}

type ClaimSandboxRequest_ProfileId struct {
	ProfileId string `protobuf:"bytes,1,opt,name=profile_id,json=profileId,oneof"`
}

type ClaimSandboxRequest_Profile struct {
	Profile *SandboxProfileSpec `protobuf:"bytes,2,opt,name=profile,oneof"`
}

func (*ClaimSandboxRequest_ProfileId) isClaimSandboxRequest_Target() {}

func (*ClaimSandboxRequest_Profile) isClaimSandboxRequest_Target() {}

type ClaimSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sandbox       *Sandbox               `protobuf:"bytes,1,req,name=sandbox" json:"sandbox,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimSandboxResponse) Reset() {
	*x = ClaimSandboxResponse{}
	mi := &file_runner_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimSandboxResponse) ProtoMessage() {}

func (x *ClaimSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimSandboxResponse.ProtoReflect.Descriptor instead.
func (*ClaimSandboxResponse) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{34}
}

func (x *ClaimSandboxResponse) GetSandbox() *Sandbox {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

type GetSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     *string                `protobuf:"bytes,1,req,name=sandbox_id,json=sandboxId" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSandboxRequest) Reset() {
	*x = GetSandboxRequest{}
	mi := &file_runner_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxRequest) ProtoMessage() {}

func (x *GetSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxRequest.ProtoReflect.Descriptor instead.
func (*GetSandboxRequest) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{35}
}

func (x *GetSandboxRequest) GetSandboxId() string {
	if x != nil && x.SandboxId != nil {
		return *x.SandboxId
	}
	return ""
}

type GetSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sandbox       *Sandbox               `protobuf:"bytes,1,req,name=sandbox" json:"sandbox,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSandboxResponse) Reset() {
	*x = GetSandboxResponse{}
	mi := &file_runner_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxResponse) ProtoMessage() {}

func (x *GetSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxResponse.ProtoReflect.Descriptor instead.
func (*GetSandboxResponse) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{36}
}

func (x *GetSandboxResponse) GetSandbox() *Sandbox {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

type ListSandboxesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      *uint32                `protobuf:"varint,1,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	PageToken     *string                `protobuf:"bytes,2,opt,name=page_token,json=pageToken" json:"page_token,omitempty"`
	LabelSelector map[string]string      `protobuf:"bytes,3,rep,name=label_selector,json=labelSelector" json:"label_selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ProfileId     *string                `protobuf:"bytes,4,opt,name=profile_id,json=profileId" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSandboxesRequest) Reset() {
	*x = ListSandboxesRequest{}
	mi := &file_runner_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSandboxesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxesRequest) ProtoMessage() {}

func (x *ListSandboxesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSandboxesRequest.ProtoReflect.Descriptor instead.
func (*ListSandboxesRequest) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{37}
}

func (x *ListSandboxesRequest) GetPageSize() uint32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListSandboxesRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

func (x *ListSandboxesRequest) GetLabelSelector() map[string]string {
	if x != nil {
		return x.LabelSelector
	}
	return nil
}

func (x *ListSandboxesRequest) GetProfileId() string {
	if x != nil && x.ProfileId != nil {
		return *x.ProfileId
	}
	return ""
}

type ListSandboxesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sandboxes     []*Sandbox             `protobuf:"bytes,1,rep,name=sandboxes" json:"sandboxes,omitempty"`
	NextPageToken *string                `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSandboxesResponse) Reset() {
	*x = ListSandboxesResponse{}
	mi := &file_runner_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSandboxesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxesResponse) ProtoMessage() {}

func (x *ListSandboxesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSandboxesResponse.ProtoReflect.Descriptor instead.
func (*ListSandboxesResponse) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{38}
}

func (x *ListSandboxesResponse) GetSandboxes() []*Sandbox {
	if x != nil {
		return x.Sandboxes
	}
	return nil
}

func (x *ListSandboxesResponse) GetNextPageToken() string {
	if x != nil && x.NextPageToken != nil {
		return *x.NextPageToken
	}
	return ""
}

type ReleaseSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     *string                `protobuf:"bytes,1,req,name=sandbox_id,json=sandboxId" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseSandboxRequest) Reset() {
	*x = ReleaseSandboxRequest{}
	mi := &file_runner_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSandboxRequest) ProtoMessage() {}

func (x *ReleaseSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSandboxRequest.ProtoReflect.Descriptor instead.
func (*ReleaseSandboxRequest) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{39}
}

func (x *ReleaseSandboxRequest) GetSandboxId() string {
	if x != nil && x.SandboxId != nil {
		return *x.SandboxId
	}
	return ""
}

type ReleaseSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseSandboxResponse) Reset() {
	*x = ReleaseSandboxResponse{}
	mi := &file_runner_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSandboxResponse) ProtoMessage() {}

func (x *ReleaseSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSandboxResponse.ProtoReflect.Descriptor instead.
func (*ReleaseSandboxResponse) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{40}
}

type PauseSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     *string                `protobuf:"bytes,1,req,name=sandbox_id,json=sandboxId" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseSandboxRequest) Reset() {
	*x = PauseSandboxRequest{}
	mi := &file_runner_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseSandboxRequest) ProtoMessage() {}

func (x *PauseSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseSandboxRequest.ProtoReflect.Descriptor instead.
func (*PauseSandboxRequest) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{41}
}

func (x *PauseSandboxRequest) GetSandboxId() string {
	if x != nil && x.SandboxId != nil {
		return *x.SandboxId
	}
	return ""
}

type PauseSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseSandboxResponse) Reset() {
	*x = PauseSandboxResponse{}
	mi := &file_runner_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseSandboxResponse) ProtoMessage() {}

func (x *PauseSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseSandboxResponse.ProtoReflect.Descriptor instead.
func (*PauseSandboxResponse) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{42}
}

type ResumeSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     *string                `protobuf:"bytes,1,req,name=sandbox_id,json=sandboxId" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeSandboxRequest) Reset() {
	*x = ResumeSandboxRequest{}
	mi := &file_runner_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeSandboxRequest) ProtoMessage() {}

func (x *ResumeSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeSandboxRequest.ProtoReflect.Descriptor instead.
func (*ResumeSandboxRequest) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{43}
}

func (x *ResumeSandboxRequest) GetSandboxId() string {
	if x != nil && x.SandboxId != nil {
		return *x.SandboxId
	}
	return ""
}

type ResumeSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeSandboxResponse) Reset() {
	*x = ResumeSandboxResponse{}
	mi := &file_runner_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeSandboxResponse) ProtoMessage() {}

func (x *ResumeSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeSandboxResponse.ProtoReflect.Descriptor instead.
func (*ResumeSandboxResponse) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{44}
}

var File_runner_proto protoreflect.FileDescriptor

const file_runner_proto_rawDesc = "" +
	"\n" +
	"\frunner.proto\x1a\x1bgoogle/protobuf/empty.proto\"-\n" +
	"\x03PTY\x12\x12\n" +
	"\x04cols\x18\x01 \x02(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x02(\rR\x04rows\"\xaf\x01\n" +
	"\rProcessConfig\x12\x18\n" +
	"\acommand\x18\x01 \x03(\tR\acommand\x126\n" +
	"\benv_vars\x18\x02 \x03(\v2\x1b.ProcessConfig.EnvVarsEntryR\aenvVars\x12\x10\n" +
	"\x03cwd\x18\x03 \x01(\tR\x03cwd\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"M\n" +
	"\vExecRequest\x12&\n" +
	"\x06config\x18\x01 \x02(\v2\x0e.ProcessConfigR\x06config\x12\x16\n" +
	"\x03pty\x18\x02 \x01(\v2\x04.PTYR\x03pty\"*\n" +
	"\tInitEvent\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x02(\x05R\tprocessId\"(\n" +
	"\tExitEvent\x12\x1b\n" +
	"\texit_code\x18\x01 \x02(\x05R\bexitCode\"\x83\x01\n" +
	"\x11AsyncExecResponse\x12\x1e\n" +
	"\x04init\x18\x01 \x01(\v2\n" +
	".InitEventR\x04init\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\fR\x06stderr\x12\x1e\n" +
	"\x04exit\x18\x04 \x01(\v2\n" +
	".ExitEventR\x04exit\"_\n" +
	"\x10SyncExecResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x02(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x02 \x02(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x02(\fR\x06stderr\"S\n" +
	"\x11SendSignalRequest\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x02(\x05R\tprocessId\x12\x1f\n" +
	"\x06signal\x18\x02 \x02(\x0e2\a.SignalR\x06signal\"\x14\n" +
	"\x12SendSignalResponse\"\x81\x01\n" +
	"\x11WriteStdinRequest\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x02(\x05R\tprocessId\x12\x16\n" +
	"\x05input\x18\x02 \x01(\fH\x00R\x05input\x12*\n" +
	"\x03eof\x18\x03 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x03eofB\t\n" +
	"\apayload\"\x14\n" +
	"\x12WriteStdinResponse\"S\n" +
	"\x0fUploadFileChunk\x12\x12\n" +
	"\x04path\x18\x01 \x02(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x02(\fR\acontent\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\"\x14\n" +
	"\x12UploadFileResponse\")\n" +
	"\x13DownloadFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x02(\tR\x04path\"-\n" +
	"\x11DownloadFileChunk\x12\x18\n" +
	"\acontent\x18\x01 \x02(\fR\acontent\"&\n" +
	"\x10ListFilesRequest\x12\x12\n" +
	"\x04path\x18\x01 \x02(\tR\x04path\"]\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04path\x18\x01 \x02(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x02(\x04R\x04size\x12\x15\n" +
	"\x06is_dir\x18\x03 \x02(\bR\x05isDir\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\rR\x04mode\"8\n" +
	"\x11ListFilesResponse\x12#\n" +
	"\aentries\x18\x01 \x03(\v2\t.FileInfoR\aentries\"E\n" +
	"\x11RemoveFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x02(\tR\x04path\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive\"\x14\n" +
	"\x12RemoveFileResponse\"\xa7\x01\n" +
	"\x0eResourceLimits\x12\x10\n" +
	"\x03cpu\x18\x01 \x02(\tR\x03cpu\x12\"\n" +
	"\rmemory_in_mbs\x18\x02 \x02(\x05R\vmemoryInMbs\x12$\n" +
	"\x0estorage_in_mbs\x18\x03 \x01(\x05R\fstorageInMbs\x129\n" +
	"\x19network_bandwidth_in_mbps\x18\x04 \x01(\x05R\x16networkBandwidthInMbps\"l\n" +
	"\x0fNetworkSettings\x12'\n" +
	"\x0fenable_internet\x18\x01 \x01(\bR\x0eenableInternet\x120\n" +
	"\x14allowed_egress_cidrs\x18\x02 \x03(\tR\x12allowedEgressCidrs\"\xf7\x04\n" +
	"\x12SandboxProfileSpec\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x02(\tR\n" +
	"templateId\x12\x10\n" +
	"\x03cwd\x18\x02 \x01(\tR\x03cwd\x121\n" +
	"\x04tags\x18\x04 \x03(\v2\x1d.SandboxProfileSpec.TagsEntryR\x04tags\x12;\n" +
	"\benv_vars\x18\x05 \x03(\v2 .SandboxProfileSpec.EnvVarsEntryR\aenvVars\x129\n" +
	"\x19auto_delete_after_seconds\x18\a \x01(\rR\x16autoDeleteAfterSeconds\x12\x16\n" +
	"\x06region\x18\t \x01(\tR\x06region\x12*\n" +
	"\anetwork\x18\n" +
	" \x01(\v2\x10.NetworkSettingsR\anetwork\x12/\n" +
	"\tresources\x18\x06 \x01(\v2\x0f.ResourceLimitsH\x00R\tresources\x124\n" +
	"\rinstance_type\x18\b \x01(\x0e2\r.InstanceTypeH\x00R\finstanceType\x12+\n" +
	"\x11ahead_concurrency\x18\v \x01(\rR\x10aheadConcurrency\x12+\n" +
	"\x11concurrency_limit\x18\f \x01(\rR\x10concurrencyLimit\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\t\n" +
	"\acompute\"w\n" +
	"\x0eSandboxProfile\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x02(\tR\tprofileId\x12'\n" +
	"\x04spec\x18\x02 \x02(\v2\x13.SandboxProfileSpecR\x04spec\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x02(\x03R\tcreatedAt\"?\n" +
	"\x14CreateProfileRequest\x12'\n" +
	"\x04spec\x18\x01 \x02(\v2\x13.SandboxProfileSpecR\x04spec\"B\n" +
	"\x15CreateProfileResponse\x12)\n" +
	"\aprofile\x18\x01 \x02(\v2\x0f.SandboxProfileR\aprofile\"2\n" +
	"\x11GetProfileRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x02(\tR\tprofileId\"?\n" +
	"\x12GetProfileResponse\x12)\n" +
	"\aprofile\x18\x01 \x02(\v2\x0f.SandboxProfileR\aprofile\"\xe3\x01\n" +
	"\x13ListProfilesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\rR\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12N\n" +
	"\x0elabel_selector\x18\x03 \x03(\v2'.ListProfilesRequest.LabelSelectorEntryR\rlabelSelector\x1a@\n" +
	"\x12LabelSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"k\n" +
	"\x14ListProfilesResponse\x12+\n" +
	"\bprofiles\x18\x01 \x03(\v2\x0f.SandboxProfileR\bprofiles\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"5\n" +
	"\x14DeleteProfileRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x02(\tR\tprofileId\"\x17\n" +
	"\x15DeleteProfileResponse\"\x8b\x01\n" +
	"\aSandbox\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x02(\tR\tsandboxId\x12#\n" +
	"\x05state\x18\x02 \x02(\x0e2\r.SandboxStateR\x05state\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x03 \x02(\tR\tprofileId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x02(\x03R\tcreatedAt\"q\n" +
	"\x13ClaimSandboxRequest\x12\x1f\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tH\x00R\tprofileId\x12/\n" +
	"\aprofile\x18\x02 \x01(\v2\x13.SandboxProfileSpecH\x00R\aprofileB\b\n" +
	"\x06target\":\n" +
	"\x14ClaimSandboxResponse\x12\"\n" +
	"\asandbox\x18\x01 \x02(\v2\b.SandboxR\asandbox\"2\n" +
	"\x11GetSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x02(\tR\tsandboxId\"8\n" +
	"\x12GetSandboxResponse\x12\"\n" +
	"\asandbox\x18\x01 \x02(\v2\b.SandboxR\asandbox\"\x84\x02\n" +
	"\x14ListSandboxesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\rR\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12O\n" +
	"\x0elabel_selector\x18\x03 \x03(\v2(.ListSandboxesRequest.LabelSelectorEntryR\rlabelSelector\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x04 \x01(\tR\tprofileId\x1a@\n" +
	"\x12LabelSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"g\n" +
	"\x15ListSandboxesResponse\x12&\n" +
	"\tsandboxes\x18\x01 \x03(\v2\b.SandboxR\tsandboxes\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"6\n" +
	"\x15ReleaseSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x02(\tR\tsandboxId\"\x18\n" +
	"\x16ReleaseSandboxResponse\"4\n" +
	"\x13PauseSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x02(\tR\tsandboxId\"\x16\n" +
	"\x14PauseSandboxResponse\"5\n" +
	"\x14ResumeSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x02(\tR\tsandboxId\"\x17\n" +
	"\x15ResumeSandboxResponse*[\n" +
	"\x06Signal\x12\x16\n" +
	"\x12SIGNAL_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSIGNAL_SIGINT\x10\x02\x12\x12\n" +
	"\x0eSIGNAL_SIGKILL\x10\t\x12\x12\n" +
	"\x0eSIGNAL_SIGTERM\x10\x0f*\xac\x01\n" +
	"\fInstanceType\x12\x1d\n" +
	"\x19INSTANCE_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13INSTANCE_TYPE_MICRO\x10\x01\x12\x17\n" +
	"\x13INSTANCE_TYPE_SMALL\x10\x02\x12\x18\n" +
	"\x14INSTANCE_TYPE_MEDIUM\x10\x03\x12\x17\n" +
	"\x13INSTANCE_TYPE_LARGE\x10\x04\x12\x18\n" +
	"\x14INSTANCE_TYPE_XLARGE\x10\x05*\xd4\x01\n" +
	"\fSandboxState\x12\x1d\n" +
	"\x19SANDBOX_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SANDBOX_STATE_PENDING\x10\x01\x12\x19\n" +
	"\x15SANDBOX_STATE_RUNNING\x10\x02\x12\x1d\n" +
	"\x19SANDBOX_STATE_TERMINATING\x10\x03\x12\x1c\n" +
	"\x18SANDBOX_STATE_TERMINATED\x10\x04\x12\x18\n" +
	"\x14SANDBOX_STATE_FAILED\x10\x05\x12\x18\n" +
	"\x14SANDBOX_STATE_PAUSED\x10\x062\x80\x03\n" +
	"\x06Runner\x12*\n" +
	"\x04Exec\x12\f.ExecRequest\x1a\x12.AsyncExecResponse0\x01\x125\n" +
	"\n" +
	"SendSignal\x12\x12.SendSignalRequest\x1a\x13.SendSignalResponse\x125\n" +
	"\n" +
	"WriteStdin\x12\x12.WriteStdinRequest\x1a\x13.WriteStdinResponse\x125\n" +
	"\n" +
	"UploadFile\x12\x10.UploadFileChunk\x1a\x13.UploadFileResponse(\x01\x12:\n" +
	"\fDownloadFile\x12\x14.DownloadFileRequest\x1a\x12.DownloadFileChunk0\x01\x122\n" +
	"\tListFiles\x12\x11.ListFilesRequest\x1a\x12.ListFilesResponse\x125\n" +
	"\n" +
	"RemoveFile\x12\x12.RemoveFileRequest\x1a\x13.RemoveFileResponse2\xf4\x04\n" +
	"\n" +
	"Management\x12>\n" +
	"\rCreateProfile\x12\x15.CreateProfileRequest\x1a\x16.CreateProfileResponse\x125\n" +
	"\n" +
	"GetProfile\x12\x12.GetProfileRequest\x1a\x13.GetProfileResponse\x12;\n" +
	"\fListProfiles\x12\x14.ListProfilesRequest\x1a\x15.ListProfilesResponse\x12>\n" +
	"\rDeleteProfile\x12\x15.DeleteProfileRequest\x1a\x16.DeleteProfileResponse\x12;\n" +
	"\fClaimSandbox\x12\x14.ClaimSandboxRequest\x1a\x15.ClaimSandboxResponse\x125\n" +
	"\n" +
	"GetSandbox\x12\x12.GetSandboxRequest\x1a\x13.GetSandboxResponse\x12>\n" +
	"\rListSandboxes\x12\x15.ListSandboxesRequest\x1a\x16.ListSandboxesResponse\x12A\n" +
	"\x0eReleaseSandbox\x12\x16.ReleaseSandboxRequest\x1a\x17.ReleaseSandboxResponse\x12;\n" +
	"\fPauseSandbox\x12\x14.PauseSandboxRequest\x1a\x15.PauseSandboxResponse\x12>\n" +
	"\rResumeSandbox\x12\x15.ResumeSandboxRequest\x1a\x16.ResumeSandboxResponseB3Z1github.com/tardigradeproj/sandbox-sdk/pkg/api;api"

var (
	file_runner_proto_rawDescOnce sync.Once
	file_runner_proto_rawDescData []byte
)

func file_runner_proto_rawDescGZIP() []byte {
	file_runner_proto_rawDescOnce.Do(func() {
		file_runner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runner_proto_rawDesc), len(file_runner_proto_rawDesc)))
	})
	return file_runner_proto_rawDescData
}

var file_runner_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 50)
var file_runner_proto_goTypes = []any{
	(Signal)(0),                    // 0: Signal
	(InstanceType)(0),              // 1: InstanceType
	(SandboxState)(0),              // 2: SandboxState
	(*PTY)(nil),                    // 3: PTY
	(*ProcessConfig)(nil),          // 4: ProcessConfig
	(*ExecRequest)(nil),            // 5: ExecRequest
	(*InitEvent)(nil),              // 6: InitEvent
	(*ExitEvent)(nil),              // 7: ExitEvent
	(*AsyncExecResponse)(nil),      // 8: AsyncExecResponse
	(*SyncExecResponse)(nil),       // 9: SyncExecResponse
	(*SendSignalRequest)(nil),      // 10: SendSignalRequest
	(*SendSignalResponse)(nil),     // 11: SendSignalResponse
	(*WriteStdinRequest)(nil),      // 12: WriteStdinRequest
	(*WriteStdinResponse)(nil),     // 13: WriteStdinResponse
	(*UploadFileChunk)(nil),        // 14: UploadFileChunk
	(*UploadFileResponse)(nil),     // 15: UploadFileResponse
	(*DownloadFileRequest)(nil),    // 16: DownloadFileRequest
	(*DownloadFileChunk)(nil),      // 17: DownloadFileChunk
	(*ListFilesRequest)(nil),       // 18: ListFilesRequest
	(*FileInfo)(nil),               // 19: FileInfo
	(*ListFilesResponse)(nil),      // 20: ListFilesResponse
	(*RemoveFileRequest)(nil),      // 21: RemoveFileRequest
	(*RemoveFileResponse)(nil),     // 22: RemoveFileResponse
	(*ResourceLimits)(nil),         // 23: ResourceLimits
	(*NetworkSettings)(nil),        // 24: NetworkSettings
	(*SandboxProfileSpec)(nil),     // 25: SandboxProfileSpec
	(*SandboxProfile)(nil),         // 26: SandboxProfile
	(*CreateProfileRequest)(nil),   // 27: CreateProfileRequest
	(*CreateProfileResponse)(nil),  // 28: CreateProfileResponse
	(*GetProfileRequest)(nil),      // 29: GetProfileRequest
	(*GetProfileResponse)(nil),     // 30: GetProfileResponse
	(*ListProfilesRequest)(nil),    // 31: ListProfilesRequest
	(*ListProfilesResponse)(nil),   // 32: ListProfilesResponse
	(*DeleteProfileRequest)(nil),   // 33: DeleteProfileRequest
	(*DeleteProfileResponse)(nil),  // 34: DeleteProfileResponse
	(*Sandbox)(nil),                // 35: Sandbox
	(*ClaimSandboxRequest)(nil),    // 36: ClaimSandboxRequest
	(*ClaimSandboxResponse)(nil),   // 37: ClaimSandboxResponse
	(*GetSandboxRequest)(nil),      // 38: GetSandboxRequest
	(*GetSandboxResponse)(nil),     // 39: GetSandboxResponse
	(*ListSandboxesRequest)(nil),   // 40: ListSandboxesRequest
	(*ListSandboxesResponse)(nil),  // 41: ListSandboxesResponse
	(*ReleaseSandboxRequest)(nil),  // 42: ReleaseSandboxRequest
	(*ReleaseSandboxResponse)(nil), // 43: ReleaseSandboxResponse
	(*PauseSandboxRequest)(nil),    // 44: PauseSandboxRequest
	(*PauseSandboxResponse)(nil),   // 45: PauseSandboxResponse
	(*ResumeSandboxRequest)(nil),   // 46: ResumeSandboxRequest
	(*ResumeSandboxResponse)(nil),  // 47: ResumeSandboxResponse
	nil,                            // 48: ProcessConfig.EnvVarsEntry
	nil,                            // 49: SandboxProfileSpec.TagsEntry
	nil,                            // 50: SandboxProfileSpec.EnvVarsEntry
	nil,                            // 51: ListProfilesRequest.LabelSelectorEntry
	nil,                            // 52: ListSandboxesRequest.LabelSelectorEntry
	(*emptypb.Empty)(nil),          // 53: google.protobuf.Empty
}
var file_runner_proto_depIdxs = []int32{
	48, // 0: ProcessConfig.env_vars:type_name -> ProcessConfig.EnvVarsEntry
	4,  // 1: ExecRequest.config:type_name -> ProcessConfig
	3,  // 2: ExecRequest.pty:type_name -> PTY
	6,  // 3: AsyncExecResponse.init:type_name -> InitEvent
	7,  // 4: AsyncExecResponse.exit:type_name -> ExitEvent
	0,  // 5: SendSignalRequest.signal:type_name -> Signal
	53, // 6: WriteStdinRequest.eof:type_name -> google.protobuf.Empty
	19, // 7: ListFilesResponse.entries:type_name -> FileInfo
	49, // 8: SandboxProfileSpec.tags:type_name -> SandboxProfileSpec.TagsEntry
	50, // 9: SandboxProfileSpec.env_vars:type_name -> SandboxProfileSpec.EnvVarsEntry
	24, // 10: SandboxProfileSpec.network:type_name -> NetworkSettings
	23, // 11: SandboxProfileSpec.resources:type_name -> ResourceLimits
	1,  // 12: SandboxProfileSpec.instance_type:type_name -> InstanceType
	25, // 13: SandboxProfile.spec:type_name -> SandboxProfileSpec
	25, // 14: CreateProfileRequest.spec:type_name -> SandboxProfileSpec
	26, // 15: CreateProfileResponse.profile:type_name -> SandboxProfile
	26, // 16: GetProfileResponse.profile:type_name -> SandboxProfile
	51, // 17: ListProfilesRequest.label_selector:type_name -> ListProfilesRequest.LabelSelectorEntry
	26, // 18: ListProfilesResponse.profiles:type_name -> SandboxProfile
	2,  // 19: Sandbox.state:type_name -> SandboxState
	25, // 20: ClaimSandboxRequest.profile:type_name -> SandboxProfileSpec
	35, // 21: ClaimSandboxResponse.sandbox:type_name -> Sandbox
	35, // 22: GetSandboxResponse.sandbox:type_name -> Sandbox
	52, // 23: ListSandboxesRequest.label_selector:type_name -> ListSandboxesRequest.LabelSelectorEntry
	35, // 24: ListSandboxesResponse.sandboxes:type_name -> Sandbox
	5,  // 25: Runner.Exec:input_type -> ExecRequest
	10, // 26: Runner.SendSignal:input_type -> SendSignalRequest
	12, // 27: Runner.WriteStdin:input_type -> WriteStdinRequest
	14, // 28: Runner.UploadFile:input_type -> UploadFileChunk
	16, // 29: Runner.DownloadFile:input_type -> DownloadFileRequest
	18, // 30: Runner.ListFiles:input_type -> ListFilesRequest
	21, // 31: Runner.RemoveFile:input_type -> RemoveFileRequest
	27, // 32: Management.CreateProfile:input_type -> CreateProfileRequest
	29, // 33: Management.GetProfile:input_type -> GetProfileRequest
	31, // 34: Management.ListProfiles:input_type -> ListProfilesRequest
	33, // 35: Management.DeleteProfile:input_type -> DeleteProfileRequest
	36, // 36: Management.ClaimSandbox:input_type -> ClaimSandboxRequest
	38, // 37: Management.GetSandbox:input_type -> GetSandboxRequest
	40, // 38: Management.ListSandboxes:input_type -> ListSandboxesRequest
	42, // 39: Management.ReleaseSandbox:input_type -> ReleaseSandboxRequest
	44, // 40: Management.PauseSandbox:input_type -> PauseSandboxRequest
	46, // 41: Management.ResumeSandbox:input_type -> ResumeSandboxRequest
	8,  // 42: Runner.Exec:output_type -> AsyncExecResponse
	11, // 43: Runner.SendSignal:output_type -> SendSignalResponse
	13, // 44: Runner.WriteStdin:output_type -> WriteStdinResponse
	15, // 45: Runner.UploadFile:output_type -> UploadFileResponse
	17, // 46: Runner.DownloadFile:output_type -> DownloadFileChunk
	20, // 47: Runner.ListFiles:output_type -> ListFilesResponse
	22, // 48: Runner.RemoveFile:output_type -> RemoveFileResponse
	28, // 49: Management.CreateProfile:output_type -> CreateProfileResponse
	30, // 50: Management.GetProfile:output_type -> GetProfileResponse
	32, // 51: Management.ListProfiles:output_type -> ListProfilesResponse
	34, // 52: Management.DeleteProfile:output_type -> DeleteProfileResponse
	37, // 53: Management.ClaimSandbox:output_type -> ClaimSandboxResponse
	39, // 54: Management.GetSandbox:output_type -> GetSandboxResponse
	41, // 55: Management.ListSandboxes:output_type -> ListSandboxesResponse
	43, // 56: Management.ReleaseSandbox:output_type -> ReleaseSandboxResponse
	45, // 57: Management.PauseSandbox:output_type -> PauseSandboxResponse
	47, // 58: Management.ResumeSandbox:output_type -> ResumeSandboxResponse
	42, // [42:59] is the sub-list for method output_type
	25, // [25:42] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_runner_proto_init() }
func file_runner_proto_init() {
	if File_runner_proto != nil {
		return
	}
	file_runner_proto_msgTypes[9].OneofWrappers = []any{
		(*WriteStdinRequest_Input)(nil),
		(*WriteStdinRequest_Eof)(nil),
	}
	file_runner_proto_msgTypes[22].OneofWrappers = []any{
		(*SandboxProfileSpec_Resources)(nil),
		(*SandboxProfileSpec_InstanceType)(nil),
	}
	file_runner_proto_msgTypes[33].OneofWrappers = []any{
		(*ClaimSandboxRequest_ProfileId)(nil),
		(*ClaimSandboxRequest_Profile)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runner_proto_rawDesc), len(file_runner_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   50,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_runner_proto_goTypes,
		DependencyIndexes: file_runner_proto_depIdxs,
		EnumInfos:         file_runner_proto_enumTypes,
		MessageInfos:      file_runner_proto_msgTypes,
	}.Build()
	File_runner_proto = out.File
	file_runner_proto_goTypes = nil
	file_runner_proto_depIdxs = nil
}
